name: PHP Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
        update-options:
          - ""
          - "--prefer-lowest"

    steps:
    - uses: actions/checkout@v4

    - name: OS info
      run: cat /etc/os-release

    - name: "Install PHP"
      uses: shivammathur/setup-php@v2
      with:
        coverage: "none"
        php-version: "${{ matrix.php-version }}"

    - name: PHP info
      run: |
        php -v
        php -m

    - name: Validate composer.json
      run: composer validate --strict --no-interaction

    - name: Install dependencies
      run: composer update --no-progress --no-interaction ${{ matrix.update-options }}

    - name: Run tests
      run: composer test

    - name: Failed test output, if any
      if: failure()
      run: for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
